---

- hosts: all
  become: true
  tasks:


  - name: CentOS - update repository index
    yum:
      update_cache: yes
    when:
      ansible_distribution == "CentOS" and ansible_virtualization_role == "guest"

  - name: CentOS - install qemu guest agent
    yum:
      name: qemu-guest-agent
      state: latest
    when:
      ansible_distribution == "CentOS" and ansible_virtualization_role == "guest"

  - name: Debian/Ubuntu - update repository index
    apt:
      update_cache: yes
    when:
      ansible_distribution in ["Debian","Ubuntu"] and ansible_virtualization_role == "guest"

  - name: Debian/Ubuntu - install qemu guest agent
    apt:
      name: qemu-guest-agent
      state: latest
    when:
      ansible_distribution in ["Debian","Ubuntu"] and ansible_virtualization_role == "guest"

