---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    yum:
      update_cache: yes

  - name: install qemu guest agent
    yum:
      name: qemu-guest-agent
      state: latest

